---
title: "Experiment 3: Collections"
output: html_notebook
---

## Vectors

### Creating a Vector

```{r}
aVect <- c(1, 3, 5, 7, 9)
print(aVect)
class(aVect)
```

Automatic coercion in list.


```{r}
vec <- c(1L, 2L, 3L)
class(vec)
str(vec)
```

### Using Sequences and Replicates

```{r}
# using sequences
xv <- seq(1, 10, by = 0.1)
# using replicate
xu <- rep('a', 5)
xv
xu
```

### Creating a Merged Vector

```{r}
c(xu, xv)
```

```{r}
friends <- c("John", "Smith", "Kenny")
class(friends)
tutorials <- c("MAT2701", "MAT2702")
merged <- c(friends, tutorials)
merged
```

### Length of a Vector

```{r}
print(length(xv))
```

### Get Specific Vector Element

```{r}
index <- 1
friends[index] # friends, position 1
```

```{r}
index <- 2:3
friends[index] # friends, position 2, 3
```

### Sorting a Vector

```{r}
x <- order(friends)
sort(friends)
friends[x]
```

```{r}
rev(friends)
rev(order(friends))
sort(friends)
```

### Remove missing Value

```{r}
myVec <- c(1, 2, 3, NA, 4)
indices <- !is.na(myVec)
myVec[indices]
```

## Random Sampling

```{r}
oneToHundred <- 1:100
aSample <- sample(oneToHundred, 20)
aSample
class(aSample)
```

```{r}
randSet <- runif(50, 1, 100)
oneToHundred[randSet]
```

```{r}
x <- sample(oneToHundred, 20, replace = T)
x
```

## Lists

```{r}
l1 <- list(1L, 2.2, "a", TRUE, Inf)
l1
```

```{r}
class(l1[[1]])
```

```{r}
names(l1) <- c('a', 'b', 'c', 'd', 'e')
l1
```

## Matrix

```{r}
matrix(1:100, nrow = 20)
```

```{r}
vec1 <- seq(1, 20, 2)
vec2 <- seq(31, 50, 2)
m1 <- rbind(vec1, vec2)
m2 <- cbind(vec1, vec2)
length(m1)
```

```{r}
str(m1)
dim(m1) <- c(4, 5)
```

```{r}
dimnames(m1)
```

```{r}
threeDStuff <- array(1:12, c(2, 2, 3))
threeDStuff
```

### Vector Recycling

### Addition, Subtraction, etc on Vectors

```{r}
m1 <- matrix(1:4, nrow = 2)
m2 <- 
```

### Generate a seq like 01230123, 000111222333

```{r}
paste(rep(0:3, 4), collapse = '')
paste(strrep(as.character(0:3), 3), collapse = '')
```


