---
title: 'Experiment 4: Conditionals and Functions'
output:
  word_document: default
  html_notebook: default
---

### Even Odd Number Test

```{r}
x <- as.integer(
  readline('Specify a number:')
)
if(x %% 2 == 0) {
 print("Even number detected.") 
} else { 
  print("Odd number detected.")
}
print(x)
```

### Prime Composite Number Test

```{r}
y <- as.numeric(
  readline("Specify a number: ")
)
print(y)
ctr <- 0
for(index in seq(1, y)) {
  if(y %% index == 0) ctr <- ctr + 1
}

if(ctr == 2) {
  print("Prime")
} else {
  print("Composite")
}
```

### Simple Calculator

```{r}
print('An expression is of the format x1 op x2, where x1, x2 are two numbers, op is an operator like +, -, *, /. Please make sure that x1, op, x2 are space seperated.')
user_input <- readline('Specify an expression! ')
parts <- strsplit(user_input, " ")
parts <- parts[[1]]

x1 <- as.numeric(parts[1])
op <- parts[2]
x2 <- as.numeric(parts[3])

value <- switch (op,
  "+" = x1 + x2,
  "-" = x1 - x2,
  "*" = x1 * x2,
  "/" = x1 / x2
)
print(
  value
)
```

## TWO THREE SIX

```{r}
numset <- 1:100
for(x in numset) {
  if(x %% 2 == 0 && x %% 3 == 0) print(paste(x, "SIX"))
  else if(x %% 2 == 0) print(paste(x, "TWO"))
  else if (x %% 3 == 0) print(paste(x, "THREE"))
}
```

### Armstrong Number Test

```{r}
user_input <- as.integer(readline("Specify a number of your choice! > "))
x_temp <- user_input
dig_sum <- 0
while(x_temp > 0) {
  digit <- x_temp %% 10;
  print(digit)
  dig_sum <- dig_sum + (digit ^ 3)
  x_temp <- x_temp %/% 10;
}
if(dig_sum == user_input) {
  print("Armstrong number detected.")
} else {
  print("Armstrong number not detected.")
}
```


## Functions

```{r}
greet <- function(name) {
  print(paste('Hello, ', name, '! You are amazing.', sep = ''))
}
greet('Dev')
```

### Write a function to get square of number in sequence

```{r}
x <- 1:20
squared <- function(i) {
  return(i*i)
}
squared(x)
```

### Write a function to print a factors of a number

```{r}
factors <- function(x) {
  y <- seq(1, x)
  return(y[x %% y == 0])
}

print('Factors of 10 are')
print(factors(10))

print('Factors of 9190 are')
print(factors(9190))
```

### Write a function to count sum of n natural numbers

```{r}
sumofnatural <- function(n) {
  return(sum(0:n))
}

print('Sum of first 10 natural numbers')
print(sumofnatural(10))
```


