---
title: 'Experiment 5: Recursions'
output:
  word_document: default
  html_notebook: default
---

## Recursions

### nCr

```{r}
fact <- function(x) {
  if(x <= 1) return(x) else return(x * fact(x - 1))
}
nCr <- function(n, r) {
  x <- fact(n) / (fact(n - r) * fact(r))
  return(x)
}

print(paste('15 items can be arranged in', nCr(15, 10), 'ways, when taking 10 items at a time'))
```

### Quick Sort

```{r}
qsort <- function(vec) {
  if(length(vec) <= 1) return(vec)
  
  pivot <- vec[length(vec)]
  vec <- vec[1:(length(vec) - 1)]
  
  a_part <- vec[vec < pivot]
  b_part <- vec[vec >= pivot]
  
  a_part <- qsort(a_part)
  b_part <- qsort(b_part)
  
  return(
    c(a_part, pivot, b_part)
  )
}

x <- c(900, 1, 3, 5, 7, 2, 4, -1, 0, 10, 100)
y <- qsort(x)

x_str <- paste(x, collapse = ' ')
y_str <- paste(y, collapse = ' ')

cat(paste('before sort: ', x_str, '\n after sort: ', y_str)) # without cat \n wont work
```

### Binary Search

```{r}
bsearch <- function(haystack, needle, lb, ub) {
  mid <- (lb + ub) %/% 2
  if(haystack[mid] == needle) {
    return(mid)
  } else if(lb == ub) {
    return(-1) # not found
  } else if(haystack[mid] < needle) {
    return(bsearch(haystack, needle, mid + 1, ub))
  } else if(haystack[mid] > needle) {
    return(bsearch(haystack, needle, lb, mid - 1))
  }
}
vec <- seq(1, 100, by = 13)
vec
index1 <- bsearch(vec, 10, 1, length(vec))
print(paste('10 found at', index1))
index2 <- bsearch(vec, 27, 1, length(vec))
print(paste('27 found at', index2))
```

## Row Wise and Column Wise Sum of Matrix

```{r}
# find row sums
rs <- function(mat1) {
  n_rows <- dim(mat1)[1]
  for(i in seq(1,n_rows)) {
    print(paste('Sum of row is', sum(mat1[i,])))
  }
}
# find column sums
cs <- function(mat1) {
  n_cols <- dim(mat1)[2]
  for(i in seq(1,n_cols)) {
    print(paste('Sum of column is', sum(mat1[,i])))
  }
}
matX <- matrix(1:100, nrow = 20)
print('Matrix is')
print(matX)
print('')
rs(matX)
print('')
cs(matX)
```

